# Generated by Django 5.2.1 on 2025-06-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_rename_created_at_message_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
