# Generated by Django 5.2.1 on 2025-06-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="sent_at",
            new_name="created_at",
        ),
    ]
