# Generated by Django 5.2.1 on 2025-06-06 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_rename_sent_at_message_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="created_at",
            new_name="sent_at",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
