# Copy content from Task 1's deployment.yaml
# Change image to version 2.0
spec:
  template:
    spec:
      containers:
      - name: django-container
        image: your-django-image:2.0  # Updated version