version: "3.9"
services:
  web:
    build:
      context: ./messaging_app
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./messaging_app:/app

  db:
    image: mysql:8.0
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: